cooling_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("coolingapp.urls"))
]

coolingapp/urls.py
from django.urls import path,include
from coolingapp import views
from django.contrib.auth import views as auth_views
from coolingapp.views import (
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)
from django.conf import settings
from django.conf.urls.static import static
from coolingapp.views import EventListView, EventCreateView, EventUpdateView, EventDeleteView

app_name = 'coolingapp'

urlpatterns = [
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name='password_reset_complete'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change_done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', view=views.index, name="index"),
    path("about", view=views.about, name="about"),
    path("dashboard/", view=views.dashboard, name="dashboard"),
    path("workpermit", view=views.workpermit, name="workpermit"),
    path("test", view=views.test, name="test"),
    path('maintenance', view=views.maintenance, name="maintenance"),
    path("account/register", view=views.register, name="register"),
    path("account/profile", view=views.profile, name="profile"),
    path("registration/login/", view=views.login_view, name="login"),
    path("logout", view=views.logout_view, name="logout"),
    path("activation/register_thankyou", view=views.register_thankyou, name="register_thankyou"),
    path("activation/activate/<str:uidb64>/<str:token>", view=views.activate, name="activate"),
    path('cooling_forecast/', views.cooling_forecast, name='cooling_forecast'),
    path('events/', EventListView.as_view(), name='event_list'),
    path('events/create/', EventCreateView.as_view(), name='event_form'),
    path('events/<int:pk>/edit/', EventUpdateView.as_view(), name='event_edit'),
    path('events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('chang_theme', view=views.chang_theme, name="chang_theme"),
    path('popup/', views.cookie_popup, name='popup'),
    path('give_consent/', views.give_consent, name='give_consent'),
    path("dashboard-overview", view=views.powerbi, name="powerbi"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coolingapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from coolingapp.models import CustomUser, Profile, CoolingForecast, Event
from django import forms

class RegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={"placeholder": "Email"}))
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Please enter username with employee ID"})
    )
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}),
        strip=False,
    )
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ("email", )

class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True, help_text="Required. 30 characters or fewer.", widget=forms.TextInput(attrs={"placeholder": "First Name"}))
    last_name = forms.CharField(max_length=30, required=True, help_text="Required. 30 characters or fewer.", widget=forms.TextInput(attrs={"placeholder": "Last Name"}))
    class Meta:
        model = CustomUser
        fields = ("first_name", "last_name")

class ExtendedProfileForm(forms.ModelForm):
    prefix = "extended"

    class Meta:
        model = Profile
        fields = ("agency", "phone", "job_positions", "employee_id")

        widgets = {
            "agency": forms.TextInput(attrs={"placeholder": "Enter your agency"}),
            "phone": forms.TextInput(attrs={"placeholder": "Enter your phone number"}),
            "job_positions": forms.TextInput(attrs={"placeholder": "Enter your job positions"}),
            "employee_id": forms.TextInput(attrs={"placeholder": "Enter your employee_id"}),
        }

class ProfilePictureForm(forms.ModelForm):
    profile_picture = forms.ImageField(label="Profile Picture")
    class Meta:
        model = Profile
        fields = ("profile_picture", )

class CoolingForecastForm(forms.ModelForm):
    class Meta:
        model = CoolingForecast
        fields = [
            'cooling_machine_number', 'InletTemp', 'OutletTemp', 'OutdoorWetBulb', 'OutdoorAirTemp', 
            'OutdoorAirHumidity', 'Kw_cooling', 'Kw_Chiller'
        ]
        widgets = {
            'cooling_machine_number': forms.TextInput(attrs={'placeholder': 'Enter Id Cooling Tower', 'class': 'cooling-input'}),
            'InletTemp': forms.NumberInput(attrs={'placeholder': 'Enter Inlet Temperature', 'class': 'cooling-input'}),
            'OutletTemp': forms.NumberInput(attrs={'placeholder': 'Enter Outlet Temperature', 'class': 'cooling-input'}),
            'OutdoorWetBulb': forms.NumberInput(attrs={'placeholder': 'Enter Outdoor Wet Bulb', 'class': 'cooling-input'}),
            'OutdoorAirTemp': forms.NumberInput(attrs={'placeholder': 'Enter Outdoor Air Temperature', 'class': 'cooling-input'}),
            'OutdoorAirHumidity': forms.NumberInput(attrs={'placeholder': 'Enter Outdoor Air Humidity', 'class': 'cooling-input'}),
            'Kw_cooling': forms.NumberInput(attrs={'placeholder': 'Enter Kw Cooling', 'class': 'cooling-input'}),
            'Kw_Chiller': forms.NumberInput(attrs={'placeholder': 'Enter Kw Chiller', 'class': 'cooling-input'}),
        }

class EventForm(forms.ModelForm):
    
    title = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Title'})
    )
    
    description = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Description'}),
        required=False
    )
    
    start_time = forms.DateTimeField(
    widget=forms.TextInput(attrs={'class': 'datetimepicker', 'placeholder': 'Select start time', 'type': 'text'}),
    )

    end_time = forms.DateTimeField(
        widget=forms.TextInput(attrs={'class': 'datetimepicker', 'placeholder': 'Select end time', 'type': 'text'}),
        required=False
    )
    
    class Meta:
        model = Event
        fields = ['title', 'description', 'start_time', 'end_time']

coolingapp/views.py
from django.core.mail import send_mail,EmailMessage
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView,  PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from coolingapp.forms import RegisterForm, UserProfileForm, ExtendedProfileForm, ProfilePictureForm, CoolingForecastForm, EventForm
from coolingapp.models import CustomUser, Profile, CoolingForecast, Event
from django.views.generic.base import TemplateView
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from itertools import groupby
from operator import attrgetter

from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes
from coolingapp.utils.activation_token_generator import activation_token_generator
from django.contrib import messages
from django.http import JsonResponse
from datetime import datetime
from django.utils import timezone

class CustomPasswordChangeDoneView(TemplateView):
    template_name = 'registration/password_change_done.html'

class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change.html'  # Specify your template
    success_url = reverse_lazy('coolingapp:password_change_done')

    def form_valid(self, form):  
            response = super().form_valid(form)
            return response

#resetpassword

class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset.html'
    success_url = reverse_lazy('coolingapp:password_reset_done')
    
class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'
    
class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = reverse_lazy('coolingapp:password_reset_complete')
    
class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'

# Create your views here.
def index(request):
    return render(request,"index.html")

@login_required
def about(request):
    return render(request,"about.html")

@login_required
def dashboard(request):
    forecasts = CoolingForecast.objects.all().order_by('cooling_machine_number')
    grouped_forecasts = {
        key: list(group)
        for key, group in groupby(forecasts, key=attrgetter('cooling_machine_number'))
    }
    context = {
        'grouped_forecasts': grouped_forecasts
    }
    return render(request, "dashboard.html", context)

@login_required
def powerbi(request):
    return render(request,"powerbi.html")

@login_required
def workpermit(request):
    return render(request,"workpermit.html")

@login_required
def test(request):
    return render(request,"test.html")

@login_required
def maintenance(request):
    return render(request,"maintenance.html")

def logout_view(request):
    logout(request)
    return render(request,'index.html')


def login_view(request):
    # Check if the user is already authenticated
    if request.user.is_authenticated:
        return render(request, 'index.html')  # Redirect to the home page or another appropriate page

    # If the request method is POST, the user submitted the login form
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # Authenticate the user
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                # Log in the user
                login(request, user)
                return render(request, 'index.html')  # Redirect to the home page or another appropriate page after successful login
    else:
        form = AuthenticationForm()

    # Render the login page with the login form
    return render(request, 'registration/login.html', {'form': form})


def register(request: HttpRequest):
    # POST
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            #Register User
            user: CustomUser = form.save(commit=False)
            user.is_active = False
            user.save()

            # login(request, user)

            #Build email body HTML
            context = {
                "protocol": request.scheme,
                "host": request.get_host(),
                "uidb64": urlsafe_base64_encode(force_bytes(user.id)),
                "token": activation_token_generator.make_token(user)
            }
            email_body = render_to_string("activation/activate_email.html", context)

            #Sent email
            email = EmailMessage(
                to=[user.email],
                subject="Activate account",
                body=email_body
            )

            email.send()

            #Redirect to thank you
            return HttpResponseRedirect(reverse("coolingapp:register_thankyou"))
    else:
        form = RegisterForm()

    context = {"form": form}
    return render(request, "account/register.html", context)


def register_thankyou(request: HttpRequest):
    return render(request,"activation/register_thankyou.html")


def activate(request: HttpRequest, uidb64: str, token: str ):
    title = "Activate account successfully"
    description = "You can now log in !"

    #Decode user id
    id = urlsafe_base64_decode(uidb64).decode()

    try:
        user: CustomUser = CustomUser.objects.get(id=id)
        if not activation_token_generator.check_token(user, token):
            raise Exception("Check token false")
        user.is_active = True
        user.save()
    except:
        print("Activate doesn't pass.")
        title = "You can't activate your account"
        description = "This link has expired or has already been activated"

    context = {"title": title, "description": description}
    return render(request,"activation/activate.html", context)



@login_required
def profile(request: HttpRequest):
    user = request.user
    #POST
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user)
        is_new_profile = False
       
        try:
            #Will update
            extended_form = ExtendedProfileForm(request.POST, instance=user.profile)
            profile_picture_form = ProfilePictureForm(request.POST, request.FILES, instance=user.profile)
        except:
            #Will create
            extended_form = ExtendedProfileForm(request.POST)
            profile_picture_form = ProfilePictureForm(request.POST)
            is_new_profile = True

        if form.is_valid() and extended_form.is_valid() and profile_picture_form.is_valid():
            form.save()
            if is_new_profile:
                # Create
                profile = extended_form.save(commit=False)
                profile.user = user  # Assign the user to the profile
                profile.save()
                profile_picture_form.instance = profile  # Assign the profile to the profile picture form's instance
                profile_picture_form.save()
            else:
                # Update
                extended_form.save()
                profile_picture_form.save()

            return HttpResponseRedirect(reverse("coolingapp:profile"))
    
    else:
        form = UserProfileForm(instance=user)
        try:
            extended_form = ExtendedProfileForm(instance=user.profile)
            profile_picture_form = ProfilePictureForm(instance=user.profile)
        except:
            extended_form =  ExtendedProfileForm()
            profile_picture_form = ProfilePictureForm()

    #GET
    context = {
        "form": form,
        "extended_form": extended_form,
        "profile_picture_form": profile_picture_form,
    }
    return render(request, "account/profile.html", context)


def password_reset_confirmation(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        # Render the HTML email template with dynamic data
        html_message = render_to_string('registration/password_reset_email.html', {
            'username': user.username,
            'protocol': settings.WEB_PROTOCAL,
            'domain': settings.WEB_DOMAIN_NAME,
            'uid': uidb64,
            'token': token,
        })

        # Send the email
        send_mail(
            'Password Reset Confirmation',  # Subject
            'This is a plain text message. Your email client may not support HTML.',  # This will be ignored for HTML emails
            'from@example.com',
            [user.email],  # Recipient's email address
            fail_silently=False,
            html_message=html_message,  # HTML content
            content_subtype='html',  # Specify that it's HTML content
        )

        # Optionally, you can return an HttpResponse or redirect to a confirmation page
        return HttpResponse("Password reset confirmation email sent.")
    else:

coolingapp/templates/about.html
{% extends "base.html" %}

{% block title %}
    <title>Line OA Linum</title>
{% endblock %}

{% block content %}
<div class="qrcode">
<img src="https://qr-official.line.me/gs/M_277zxncs_BW.png?oat_content=qr">
</div>
{% endblock %}

coolingapp/templates/cookie_popup.html
<div class="cookie-popup" id="cookiePopup" {% if consent %} style="display: none;" {% endif %} >
          <p class="cookietext">🍪 This website uses cookies to provide you with a better user experience. By clicking "Allow," you consent to our use of cookies.</p>
          <form class="cookiepopupform" id="allowForm">
              {% csrf_token %}
              <button class="cookiebutton" type="submit" id="allowButton"><i class="fa fa-paper-plane" aria-hidden="true"></i> Allow</button>
          </form>
      </div>
      
      <script>
      // JavaScript to handle closing the cookie popup
      const allowForm = document.getElementById('allowForm');
      const cookiePopup = document.getElementById('cookiePopup');
      
      allowForm.addEventListener('submit', (event) => {
        event.preventDefault(); // Prevent the form submission
      
        // Hide the cookie pop-up
        cookiePopup.style.display = 'none';
      
        // Set a cookie to remember the user's consent decision for 30 days (or use local storage)
        const now = new Date();
        now.setDate(now.getDate() + 30);
        document.cookie = 'cookie_consent=true; expires=' + now.toUTCString() + '; path=/';
      
        // Send an AJAX request to update the user's consent status in the backend
        fetch("{% url 'coolingapp:give_consent' %}", {
          method: "POST",
          headers: {
            "X-CSRFToken": getCookie("csrftoken"),
          },
        });
      });
      
      // Helper function to get CSRF token for AJAX request
      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          const cookies = document.cookie.split(";");
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      
      // Check if the user has already given consent using cookies
      if (document.cookie.includes('cookie_consent=true')) {
        cookiePopup.style.display = 'none'; // Hide the popup if consent is given
      }
      </script>

coolingapp/templates/cooling_forecast.html
{% extends "base.html" %}

{% block title %}
    <title>Cooling Forecast</title>
{% endblock %}

{% block content %}
<main>
<section class="content_coolingforecast">
  <div class="content_coolingform">
    <form class="coolingform" method="post">
      {% csrf_token %}
      <h1 class="cooling_title" >Cooling Tower Forecast</h1>
      <div class="form-field">
        <label for="labelidcooling" class="labelidcooling">ID Cooling Tower</label>
        <div class="idcooling">{{ form.cooling_machine_number }}</div>
      </div>
      <div class="form-field">
        <label for="id_cooling_input">InletTemp <i class="fa fa-thermometer-empty" aria-hidden="true"></i></label>
        <div class="cooling_input">{{ form.InletTemp }}</div>
      </div>
      <div class="form-field">
        <label for="id_cooling_input">OutletTemp <i class="fa fa-thermometer-empty" aria-hidden="true"></i></label>
        <div class="cooling_input">{{ form.OutletTemp }}</div>
      </div>
      <div class="form-field">
        <label for="id_cooling_input">OutdoorWetBulb <i class="fa fa-snowflake-o" aria-hidden="true"></i></label>
        <div class="cooling_input">{{ form.OutdoorWetBulb }}</div>
      </div>
      <div class="form-field">
        <label for="id_cooling_input">OutdoorAirTemp <i class="fa fa-sun-o" aria-hidden="true"></i></label>
        <div class="cooling_input">{{ form.OutdoorAirTemp }}</div>
      </div>
      <div class="form-field">
        <label for="id_cooling_input">OutdoorAirHumidity <i class="fa fa-thermometer-three-quarters" aria-hidden="true"></i></label>
        <div class="cooling_input">{{ form.OutdoorAirHumidity }}</div>
      </div>
      <div class="form-field">
        <label for="id_cooling_input">Kw Cooling Tower <i class="fa fa-bolt" aria-hidden="true"></i></label>
        <div class="cooling_input">{{ form.Kw_cooling }}</div>
      </div>
      <div class="form-field">
        <label for="id_cooling_input">Kw Chiller <i class="fa fa-bolt" aria-hidden="true"></i></label>
        <div class="cooling_input">{{ form.Kw_Chiller }}</div>
      </div>
      <p>
        <button type="submit" class="buttonsubmit-prediction">Prediction <i class="fa fa-rocket" aria-hidden="true"></i></button>
      </p> 
    </form>
  </div>
  <div class="content_right_side">
    <img src="/static/assets/img/howtoprecition_3.png" style="max-width: 600px;">
  </div>
</section>
</main>
{% endblock %}

coolingapp/templates/dashboard.html
{% extends "base.html" %}

{% block title %}
    <title>Dashboard</title>
{% endblock %}

{% block content %}
    <h1 class="Dashboard">Cooling tower forecast results</h1>  
    {% for machine_id, machine_forecasts in grouped_forecasts.items %}
    <h2 class="cooling_title">Cooling Machine ID: {{ machine_id }}</h2>
    <div class="table_cooling">
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>ID</th>
                <th>Inlet Temp</th>
                <th>Outlet Temp</th>
                <th>Outdoor WetBulb</th>
                <th>Outdoor AirTemp</th>
                <th>Outdoor AirHumidity</th>
                <th>Kw cooling</th>
                <th>Kw Chiller</th>
                <th>Delta_T</th>
                <th>Approach_Temperature</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for forecast in machine_forecasts %}
            <tr>
                <td>{{ forecast.recorded_at }}</td>
                <td>{{ forecast.cooling_machine_number }}</td>
                <td>{{ forecast.InletTemp }}</td>
                <td>{{ forecast.OutletTemp }}</td>
                <td>{{ forecast.OutdoorWetBulb }}</td>
                <td>{{ forecast.OutdoorAirTemp }}</td>
                <td>{{ forecast.OutdoorAirHumidity }}</td>
                <td>{{ forecast.Kw_cooling }}</td>
                <td>{{ forecast.Kw_Chiller }}</td>
                <td>{{ forecast.Delta_T }}</td>
                <td>{{ forecast.Approach_Temperature }}</td>
                <td>{{ forecast.Status }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>  
</div>
{% endfor %}

{% if not grouped_forecasts %}
    <p class="cooling_title">No forecast data available.</p]>
{% endif %}

{% endblock %}

coolingapp/templates/powerbi.html
{% extends 'base.html' %}

{% block title %}
  <title>Dashboard</title>
{% endblock %}

{% block content %}
  <div class="reportdashboard">
    <div class="iframe-container">
      <div class="reportelectricity_dashboard">
        <h1 class="dashboard_title">การใช้พลังงานไฟฟ้า</h1>
        <iframe title="Report Section" width="600" height="373.5" src="https://app.powerbi.com/view?r=eyJrIjoiYjJiZDUwMjAtZmRhOS00YzA3LTg5YjctM2Y3MDk1MWI5NDgyIiwidCI6IjBlY2I3YzgyLTFiODQtNGIzNi1hZGVmLTIwODFiNWMxMTI1YiIsImMiOjEwfQ%3D%3D" frameborder="0" allowFullScreen="true"></iframe>
      </div>
    </div>

    <div class="iframe-container">
      <div class="reportwater_dashboard">
        <h1 class="dashboard_title">การใช้น้ำประปา</h1>
        <iframe title="Report Section" width="600" height="373.5" src="https://app.powerbi.com/view?r=eyJrIjoiZTI3ZWQzNTUtOGEwZS00OGRjLWI2YTEtMGYzNjczNGYzZjY4IiwidCI6IjBlY2I3YzgyLTFiODQtNGIzNi1hZGVmLTIwODFiNWMxMTI1YiIsImMiOjEwfQ%3D%3D" frameborder="0" allowFullScreen="true"></iframe>
      </div>
    </div>

    <div class="iframe-container">
      <div class="maintenance_dashboard">
        <h1 class="dashboard_title">รายงานการแจ้งซ่อม</h1>
        <iframe title="Maintenance Dashboard อก.งอ" width="600" height="373.5" src="https://app.powerbi.com/view?r=eyJrIjoiYThiNjk5Y2YtM2FmZi00YzcxLThmYWYtODQ3MGE1YTU0NTIzIiwidCI6IjBlY2I3YzgyLTFiODQtNGIzNi1hZGVmLTIwODFiNWMxMTI1YiIsImMiOjEwfQ%3D%3D" frameborder="0" allowFullScreen="true"></iframe>
      </div>
    </div>
  </div>
{% endblock %}

coolingapp/templates/test.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}
   