cooling_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("coolingapp.urls"))
]

coolingapp/urls.py
from django.urls import path,include
from coolingapp import views
from django.contrib.auth import views as auth_views
from coolingapp.views import (
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)
from django.conf import settings
from django.conf.urls.static import static
from coolingapp.views import EventListView, EventCreateView, EventUpdateView, EventDeleteView

app_name = 'coolingapp'

urlpatterns = [
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name='password_reset_complete'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change_done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', view=views.index, name="index"),
    path("about", view=views.about, name="about"),
    path("dashboard/", view=views.dashboard, name="dashboard"),
    path("workpermit", view=views.workpermit, name="workpermit"),
    path("test", view=views.test, name="test"),
    path('maintenance', view=views.maintenance, name="maintenance"),
    path("account/register", view=views.register, name="register"),
    path("account/profile", view=views.profile, name="profile"),
    path("registration/login/", view=views.login_view, name="login"),
    path("logout", view=views.logout_view, name="logout"),
    path("activation/register_thankyou", view=views.register_thankyou, name="register_thankyou"),
    path("activation/activate/<str:uidb64>/<str:token>", view=views.activate, name="activate"),
    path('cooling_forecast/', views.cooling_forecast, name='cooling_forecast'),
    path('events/', EventListView.as_view(), name='event_list'),
    path('events/create/', EventCreateView.as_view(), name='event_form'),
    path('events/<int:pk>/edit/', EventUpdateView.as_view(), name='event_edit'),
    path('events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_delete'),
    path('chang_theme', view=views.chang_theme, name="chang_theme"),
    path('popup/', views.cookie_popup, name='popup'),
    path('give_consent/', views.give_consent, name='give_consent'),
    path("dashboard-overview", view=views.powerbi, name="powerbi"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coolingapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from joblib import load
from datetime import datetime
from django.utils import timezone
from linebot import LineBotApi
from linebot.models import TextSendMessage
from linebot.exceptions import LineBotApiError
from decouple import config

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

class Profile(models.Model):
    agency = models.CharField(default="")
    phone = models.CharField(max_length=10, default="")
    job_positions = models.CharField(max_length=100, default="")
    employee_id = models.CharField(max_length=100, default="")
    profile_picture = models.ImageField(blank=True, null=True)
    user = models.OneToOneField("coolingapp.CustomUser", on_delete=models.CASCADE)
    # Add the is_profile_updated field
    is_profile_updated = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

model_random_forest = load('coolingapp/model_ml/model_random_forest_cooling.pkl')

LINE_CHANNEL_ACCESS_TOKEN = config('LINE_CHANNEL_ACCESS_TOKEN')
LINE_USER_ID = config('LINE_USER_ID')


line_bot_api = LineBotApi(LINE_CHANNEL_ACCESS_TOKEN)

class CoolingForecast(models.Model):
    recorded_at = models.DateTimeField(default=timezone.now)
    cooling_machine_number = models.CharField(max_length=100, blank=True, null=True)
    InletTemp = models.FloatField()
    OutletTemp = models.FloatField()
    OutdoorWetBulb = models.FloatField()
    OutdoorAirTemp = models.FloatField()
    OutdoorAirHumidity = models.FloatField()
    Kw_cooling = models.FloatField()
    Kw_Chiller = models.FloatField()
    Delta_T = models.FloatField(null=True, blank=True)
    Approach_Temperature = models.FloatField(null=True, blank=True)
    Status = models.IntegerField(null=True, blank=True)

    @property
    def year(self):
        return self.recorded_at.year

    @property
    def month(self):
        return self.recorded_at.month

    @property
    def day(self):
        return self.recorded_at.day

    @property
    def hour(self):
        return self.recorded_at.hour

    @property
    def minute(self):
        return self.recorded_at.minute

    @property
    def converted_Minute(self):
        if 1 <= self.minute <= 15:
            return 1
        elif 16 <= self.minute <= 30:
            return 2
        elif 31 <= self.minute <= 45:
            return 3
        elif 46 <= self.minute <= 60:
            return 4
        return None

    
    @property
    def converted_InletTemp(self):
        if self.InletTemp < 95:
            return 1
        elif self.InletTemp == 95:
            return 2
        else:
            return 3

    @property
    def converted_OutletTemp(self):
        if self.OutletTemp < 85:
            return 1
        elif self.OutletTemp == 85:
            return 2
        else:
            return 3

    @property
    def converted_OutdoorWetBulb(self):
        if self.OutdoorWetBulb < 78:
            return 1
        elif self.OutdoorWetBulb == 78:
            return 2
        else:
            return 3

    @property
    def converted_OutdoorAirTemp(self):
        if self.OutdoorAirTemp < 80.6:
            return 1
        elif 80.6 <= self.OutdoorAirTemp <= 87.389:
            return 2
        else:
            return 3

    @property
    def converted_OutdoorAirHumidity(self):
        if self.OutdoorAirHumidity < 57.854:
            return 1
        elif 57.854 <= self.OutdoorAirHumidity <= 79.9:
            return 2
        else:
            return 3

    @property
    def converted_Kw_cooling(self):
        if self.Kw_cooling < 20.333:
            return 1
        else:
            return 2

    @property
    def converted_Kw_Chiller(self):
        if self.Kw_Chiller == 0:
            return 0
        elif self.Kw_Chiller <= 1176.038:
            return 1
        else:
            return 2

    @property
    def converted_Delta_T(self):
        if self.Delta_T < 7:
            return 1
        elif 7 <= self.Delta_T < 10:
            return 2
        else:
            return 3

    @property
    def converted_Approach_Temperature(self):
        if self.Approach_Temperature < 0:
            return 1
        elif 0 <= self.Approach_Temperature < 7:
            return 2
        else:
            return 3

    def notify_line(self, message):
        try:
            line_bot_api.push_message(LINE_USER_ID, TextSendMessage(text=message))
        except LineBotApiError as e:
            print(f"Failed to send message: {e}")

    def predict_status(self):
        # Compute Delta_T and Approach_Temperature
        self.Delta_T = self.InletTemp - self.OutletTemp
        self.Approach_Temperature = self.OutletTemp - self.OutdoorWetBulb

        # Prepare data for prediction using the converted properties
        data_for_prediction = [[
            self.year, 
            self.month, 
            self.day, 
            self.hour, 
            self.converted_Minute,
            self.converted_InletTemp, 
            self.converted_OutletTemp, 
            self.converted_OutdoorWetBulb, 
            self.converted_OutdoorAirTemp, 
            self.converted_OutdoorAirHumidity, 
            self.converted_Kw_cooling, 
            self.converted_Kw_Chiller, 
            self.converted_Delta_T, 
            self.converted_Approach_Temperature
        ]]

        forecast_result = model_random_forest.predict(data_for_prediction)
        print(f"Model prediction: {forecast_result}")
        
        self.Status = forecast_result[0]
        print(f"Status before save: {self.Status}")
    
        if self.Status == 1:
            self.notify_line('The forecast status is 1! Please check the cooling tower.')

    def save(self, *args, **kwargs):
        # Step 3 : Forecasting
        self.predict_status()
        print(f"Status at save: {self.Status}") 

        # Call the parent class's save method
        super().save(*args, **kwargs)

class Event(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    description = models.CharField(blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class CookieConsent(models.Model):
    user = models.ForeignKey('coolingapp.CustomUser',
                             on_delete=models.CASCADE)
    consent_given = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.consent_given}'

coolingapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from coolingapp.models import CustomUser, Profile, CoolingForecast, Event
from django import forms

class RegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={"placeholder": "Email"}))
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Please enter username with employee ID"})
    )
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}),
        strip=False,
    )
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ("email", )

class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True, help_text="Required. 30 characters or fewer.", widget=forms.TextInput(attrs={"placeholder": "First Name"}))
    last_name = forms.CharField(max_length=30, required=True, help_text="Required. 30 characters or fewer.", widget=forms.TextInput(attrs={"placeholder": "Last Name"}))
    class Meta:
        model = CustomUser
        fields = ("first_name", "last_name")

class ExtendedProfileForm(forms.ModelForm):
    prefix = "extended"

    class Meta:
        model = Profile
        fields = ("agency", "phone", "job_positions", "employee_id")

        widgets = {
            "agency": forms.TextInput(attrs={"placeholder": "Enter your agency"}),
            "phone": forms.TextInput(attrs={"placeholder": "Enter your phone number"}),
            "job_positions": forms.TextInput(attrs={"placeholder": "Enter your job positions"}),
            "employee_id": forms.TextInput(attrs={"placeholder": "Enter your employee_id"}),
        }

class ProfilePictureForm(forms.ModelForm):
    profile_picture = forms.ImageField(label="Profile Picture")
    class Meta:
        model = Profile
        fields = ("profile_picture", )

class CoolingForecastForm(forms.ModelForm):
    class Meta:
        model = CoolingForecast
        fields = [
            'cooling_machine_number', 'InletTemp', 'OutletTemp', 'OutdoorWetBulb', 'OutdoorAirTemp', 
            'OutdoorAirHumidity', 'Kw_cooling', 'Kw_Chiller'
        ]
        widgets = {
            'cooling_machine_number': forms.TextInput(attrs={'placeholder': 'Enter Id Cooling Tower', 'class': 'cooling-input'}),
            'InletTemp': forms.NumberInput(attrs={'placeholder': 'Enter Inlet Temperature', 'class': 'cooling-input'}),
            'OutletTemp': forms.NumberInput(attrs={'placeholder': 'Enter Outlet Temperature', 'class': 'cooling-input'}),
            'OutdoorWetBulb': forms.NumberInput(attrs={'placeholder': 'Enter Outdoor Wet Bulb', 'class': 'cooling-input'}),
            'OutdoorAirTemp': forms.NumberInput(attrs={'placeholder': 'Enter Outdoor Air Temperature', 'class': 'cooling-input'}),
            'OutdoorAirHumidity': forms.NumberInput(attrs={'placeholder': 'Enter Outdoor Air Humidity', 'class': 'cooling-input'}),
            'Kw_cooling': forms.NumberInput(attrs={'placeholder': 'Enter Kw Cooling', 'class': 'cooling-input'}),
            'Kw_Chiller': forms.NumberInput(attrs={'placeholder': 'Enter Kw Chiller', 'class': 'cooling-input'}),
        }

class EventForm(forms.ModelForm):
    
    title = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Title'})
    )
    
    description = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Description'}),
        required=False
    )
    
    start_time = forms.DateTimeField(
    widget=forms.TextInput(attrs={'class': 'datetimepicker', 'placeholder': 'Select start time', 'type': 'text'}),
    )

    end_time = forms.DateTimeField(
        widget=forms.TextInput(attrs={'class': 'datetimepicker', 'placeholder': 'Select end time', 'type': 'text'}),
        required=False
    )
    
    class Meta:
        model = Event
        fields = ['title', 'description', 'start_time', 'end_time']

coolingapp/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="content-deletelist">
    <form method="post">
    <p  class="titledeletelist" > Are you sure you want to delete </p>
    <p class="objecttitle" >{{ object.title }}?</p>
    {% csrf_token %}
    <button class="deletelist" type="submit">Yes, Delete</button>
</form>
</div>
<!-- convas - tree -->
<canvas role="img" aria-label="A tree growing until it bears fruit, dropping its fruit, shrinking, and repeating the cycle"></canvas>

<script>

    window.addEventListener("DOMContentLoaded",() => {
        const t = new Tree("canvas");
    });
    
    class Tree {
        constructor(qs) {
            this.C = document.querySelector(qs);
            this.c = this.C?.getContext("2d");
            this.S = window.devicePixelRatio;
            this.W = 800;
            this.H = 800;
            this.branches = [];
            this.darkTheme = false;
            this.debug = false;
            this.decaying = false;
            this.floorY = 685;
            this.fruit = [];
            this.gravity = 0.098;
            this.loopDelay = 500;
            this.loopEnd = Utils.dateValue;
            this.maxGenerations = 10;
    
            if (this.C) this.init();
        }
        get allBranchesComplete() {
            const { branches, maxGenerations } = this;
    
            return branches.filter(b => {
                const isLastGen = b.generation === maxGenerations;
                return b.progress >= 1 && isLastGen;
            }).length > 0;
        }
        get allFruitComplete() {
            return !!this.fruit.length && this.fruit.every(f => f.progress === 1);
        }
        get allFruitFalling() {
            return !!this.fruit.length && this.fruit.every(f => f.timeUntilFall <= 0);
        }
        get debugInfo() {
            return [
                { item: 'Pixel Ratio', value: this.S },
                { item: 'Branches', value: this.branches.length },
                { item: 'Branches Complete', value: this.allBranchesComplete },
                { item: 'Decaying', value: this.decaying },
                { item: 'Fruit', value: this.fruit.length },
                { item: 'Fruit Complete', value: this.allFruitComplete }
            ];
        }
        get lastGeneration() {
            const genIntegers = this.branches.map(b => b.generation);
            return [...new Set(genIntegers)].pop();
        }
        get trunk() {
            return {
                angle: 0,
                angleInc: 20,
                decaySpeed: 0.0625,
                diameter: 10,
                distance: 120,
                distanceFade: 0.2,
                generation: 1,
                growthSpeed: 0.04,
                hadBranches: false,
                progress: 0,
                x1: 400,
                y1: 680,
                x2: 400,
                y2: 560
            };
        }
        detectTheme(mq) {
            this.darkTheme = mq.matches;
        }
        draw() {
            const { c, W, H, debug, branches, fruit } = this;
    
            c.clearRect(0,0,W,H);
    
            const lightness = this.darkTheme ? 90 : 10;
            const foreground = `#0072CE`;
            c.fillStyle = '#FFD228';
            c.strokeStyle = foreground;
    
            // debug info
            if (debug === true) {
                const textX = 24;
    
                this.debugInfo.forEach((d,i) => {
                    c.fillText(`${d.item}: ${d.value}`,textX,24 * (i + 1));
                });
            }
    
            // branches
            branches.forEach(b => {
                c.lineWidth = b.diameter;
                c.beginPath();
                c.moveTo(b.x1,b.y1);
                c.lineTo(
                    b.x1 + (b.x2 - b.x1) * b.progress,
                    b.y1 + (b.y2 - b.y1) * b.progress
                );
                c.stroke();
                c.closePath();
            });
    
            // fruit
            fruit.forEach(f => {
                c.globalAlpha = f.decayTime	< f.decayFrames ? f.decayTime / f.decayFrames : 1;
                c.beginPath();
                c.arc(f.x,f.y,f.r * f.progress,0,2 * Math.PI);
                c.fill();
                c.closePath();
                c.globalAlpha = 1;
            });
        }
        grow() {
            // start with the trunk
            if (!this.branches.length && Utils.dateValue - this.loopEnd > this.loopDelay) {
                this.branches.push(this.trunk);
            }
    
            if (!this.allBranchesComplete) {
                this.branches.forEach(b => {
                    if (b.progress < 1) {
                        // branch growth
                        b.progress += b.growthSpeed;
    
                        if (b.progress > 1) {
                            b.progress = 1;
    
                            // grow fruit if the generation is the last
                            if (b.generation === this.maxGenerations) {
                                this.fruit.push({
                                    decayFrames: 18,
                                    decayTime: 150,
                                    progress: 0,
                                    speed: 0.04,
                                    timeUntilFall: Utils.randomInt(0,300),
                                    x: b.x2,
                                    y: b.y2,
                                    r: Utils.randomInt(4,6),
                                    restitution: 0.2 * (1 - b.y2 / this.floorY),
                                    yVelocity: 0
                                });
                            }
                        }
    
                    } else if (!b.hadBranches && b.generation < this.maxGenerations) {
                        b.hadBranches = true;
                        // create two new branches
                        const lean = 5;
                        const angleLeft = b.angle - (b.angleInc + Utils.randomInt(-lean,lean));
                        const angleRight = b.angle + (b.angleInc + Utils.randomInt(-lean,lean));
                        const distance = b.distance * (1 - b.distanceFade);
                        const generation = b.generation + 1;
    
                        const leftBranch = {
                            angle: angleLeft,
                            angleInc: b.angleInc,
                            decaySpeed: b.decaySpeed,
                            diameter: Math.floor(b.diameter * 0.9),
                            distance,
                            distanceFade: b.distanceFade,
                            generation,
                            growthSpeed: b.growthSpeed,
                            hadBranches: false,
                            progress: 0,
                            x1: b.x2,
                            y1: b.y2,
                            x2: b.x2 + Utils.endPointX(angleLeft,distance),
                            y2: b.y2 - Utils.endPointY(angleLeft,distance)
                        };
    
                        const rightBranch = {...leftBranch};
                        rightBranch.angle = angleRight;
                        rightBranch.x2 = b.x2 + Utils.endPointX(angleRight,distance);
                        rightBranch.y2 = b.y2 - Utils.endPointY(angleRight,distance);
    
                        this.branches.push(leftBranch,rightBranch);
                    }
                });
            }
            if (!this.allFruitComplete) {
                this.fruit.forEach(f => {
                    if (f.progress < 1) {
                        f.progress += f.speed;
    
                        if (f.progress > 1) f.progress = 1;
                    }
                });
            }
    
            if (this.allBranchesComplete && this.allFruitComplete) this.decaying = true;
        }
        decay() {
            if (this.fruit.length) {
                // fruit fall
                this.fruit = this.fruit.filter(f => f.decayTime > 0);
    
                this.fruit.forEach(f => {
                    if (f.timeUntilFall <= 0) {
                        f.y += f.yVelocity;
                        f.yVelocity += this.gravity;
    
                        const bottom = this.floorY - f.r;
    
                        if (f.y >= bottom) {
                            f.y = bottom;
                            f.yVelocity *= -f.restitution;
                        }
    
                        --f.decayTime;
    
                    } else if (!f.decaying) {
                        --f.timeUntilFall;
                    }
                });
            }
            if (this.allFruitFalling || !this.fruit.length) {
                // branch decay
                this.branches = this.branches.filter(b => b.progress > 0);
    
                this.branches.forEach(b => {
                    if (b.generation === this.lastGeneration) b.progress -= b.decaySpeed;
                });
            }
            if (!this.branches.length && !this.fruit.length) {
                // back to the trunk
                this.decaying = false;
                this.loopEnd = Utils.dateValue;
            }
        }
        init() {
            this.setupCanvas();
            this.setupThemeDetection();
            this.run();
        }
        run() {
            this.draw();
    
            if (this.decaying) this.decay();
            else this.grow();
    
            requestAnimationFrame(this.run.bind(this));
        }
        setupCanvas() {
            const { C, c, W, H, S } = this;
    
            // properly scale the canvas based on the pixel ratio
            C.width = W * S;
            C.height = H * S;
            C.style.width = "auto";
            C.style.height = "100%";
            c.scale(S,S);
    
            // set unchanging styles
            c.font = "16px sans-serif";
            c.lineCap = "round";
            c.lineJoin = "round";
        }
        setupThemeDetection() {
            if (window.matchMedia) {
                const mq = window.matchMedia("(prefers-color-scheme: dark)");
                this.detectTheme(mq);
                mq.addListener(this.detectTheme.bind(this));
            }
        }
    }
    
    class Utils {
        static get dateValue() {
            return +new Date();
        }
        static endPointX(angleInDeg,distance) {
            return Math.sin(angleInDeg * Math.PI / 180) * distance;
        }
        static endPointY(angleInDeg,distance) {
            return Math.cos(angleInDeg * Math.PI / 180) * distance;
        }
        static randomInt(min,max) {
            return min + Math.round(Math.random() * (max - min));
        }
    }
    
    </script>
{% endblock %}

coolingapp/templates/events/event_form.html
{% extends 'base.html' %}

{% block content %}
<main>
<section class="content-section content-section-single">
<div class="content-container">
<div class="form-container">
    <form method="post" class="event-form">
        <svg preserveAspectRatio="none" viewBox="0 0 100 25">
            <defs>
              <pattern id="pattern" x="0" y="0" width="0.2" height="1">
                <rect x="0" y="0" width="10" height="15" fill="#fff" />
                <circle cx="5" cy="15" r="5" fill="#fff" />
                <rect x="10" y="0" width="10" height="15" fill="currentColor" />
                <circle cx="15" cy="15" r="5" fill="currentColor" />
              </pattern>
            </defs>
            <g id="roof">
              <rect x="0" y="0" width="100" height="5" fill="url(#pattern)" />
              <rect x="0" y="0" width="100" height="5" fill="#00000022" />
            </g>
            <rect x="0" y="5" width="100" height="20" fill="url(#pattern)" />
          </svg>
        <h1 class="cooling_title" >Event</h1>
        {% csrf_token %}
        <div class="form-field">
            <label for="id_event_title">Title <i class="fa fa-book" aria-hidden="true"></i></label>
            <div class="input_event_title">{{ form.title }}</div>
        </div>
        <div class="form-field">
            <label for="id_event_description">Description <i class="fa fa-pencil" aria-hidden="true"></i></label>
            <div class="input_event_description">{{ form.description }}</div>
        </div>
        <div class="form-field">
            <label for="id_start_time">Start Event <i class="fa fa-calendar-o" aria-hidden="true"></i></label>
            <div class="datetimepicker">{{ form.start_time }}</div>
        </div>
        <div class="form-field">
            <label for="id_end_time">End Event <i class="fa fa-calendar-o" aria-hidden="true"></i></label>
            <div class="datetimepicker">{{ form.end_time }}</div>
        </div>        
        <div class="form-actions">
            <button type="submit" class="buttonsubmit">Save Event</button>
        </div>
    </form>
</div>
</div>
</section>
</main>
<script>
    $(document).ready(function(){
        $('#id_start_time').datetimepicker({
            format:'Y-m-d H:i',
        });
        
        $('#id_end_time').datetimepicker({
            format:'Y-m-d H:i',
        });
    });
</script>


{% endblock %}

coolingapp/templates/events/event_list.html
{% extends 'base.html' %}

{% block content %}
<div class="events-container">
    <p class="title_event"> Event List : {{ user.username }}</p>
    {% for event in events %}

        <div class="event-item">
            <h3 class="event-title">{{ event.title }}</h3>
            <p class="event-description">{{ event.description }}</p>
            <div class="event-date-time">
                <span class="event-start-time">{{ event.start_time }}</span> -
                <span class="event-end-time">{{ event.end_time }}</span>
            </div>
            <div class="event-actions">
                <a href="{% url 'coolingapp:event_edit' event.id %}" class="event-edit-btn">Edit</a>
                <a href="{% url 'coolingapp:event_delete' event.id %}" class="event-delete-btn">Delete</a>
            </div>
        </div>
    {% endfor %}
</div>
<div class="dog_container">
    <div class="dog">
              <div class="dog-head">
                        <div class="dog-ears ears-left"></div>
                        <div class="dog-ears ears-right"></div>
                        <div class="dog-eyes"></div>
                        <div class="dog-mouth">
                                  <div class="dog-nose"></div>
                                  <div class="dog-tongue"></div>
                        </div>
              </div>
              <div class="dog-tail"></div>
              <div class="dog-body">
                        <div class="dog-foot"></div>
              </div>
              <div class="ball"></div>
    </div>
</div>
{% endblock %}